# Project 1 - Day 1

In [73]:
# importing the dataset 

import pandas as pd
from pathlib import Path

df = pd.read_csv('./Resources/canada_household_econimic_data.csv')
df.head()

,"Income, consumption and savings",2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Household disposable income,"615,286","642,584","663,239","695,238","721,510","774,375","816,321","862,404","884,783",...,"1,046,791","1,081,654","1,129,875","1,132,763","1,189,366","1,224,919","1,280,362","1,387,360","1,444,569","1,520,693"
1,Compensation of employees,"574,278","596,782","620,600","656,154","692,609","737,321","782,564","818,108","810,556",...,"959,181","996,247","1,024,742","1,024,142","1,066,523","1,122,304","1,168,597","1,155,842","1,264,592","1,383,129"
2,Net mixed income,"107,636","111,748","116,533","122,301","125,661","131,002","138,842","143,917","144,671",...,"167,712","172,078","177,994","183,581","190,323","195,618","207,999","207,211","217,267","237,720"
3,Property income received,"116,942","109,346","108,675","113,209","122,970","137,105","153,667","160,013","152,106",...,"175,342","181,876","198,218","189,502","202,189","202,278","217,587","212,221","215,883","241,202"
4,Less: property income paid,"41,204","37,300","39,081","40,156","43,309","52,632","61,313","63,921","55,559",...,"56,232","55,857","56,033","56,405","60,186","70,213","79,808","72,579","66,922","85,866"

In [76]:
df.rename(columns={'Income, consumption and savings':'Segment'},inplace=True)
df.set_index('Segment',inplace = True)
df

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Segment,,,,,,,,,,,,,,,,,,,,,
Household disposable income,"615,286","642,584","663,239","695,238","721,510","774,375","816,321","862,404","884,783","928,091",...,"1,046,791","1,081,654","1,129,875","1,132,763","1,189,366","1,224,919","1,280,362","1,387,360","1,444,569","1,520,693"
Compensation of employees,"574,278","596,782","620,600","656,154","692,609","737,321","782,564","818,108","810,556","835,940",...,"959,181","996,247","1,024,742","1,024,142","1,066,523","1,122,304","1,168,597","1,155,842","1,264,592","1,383,129"
Net mixed income,"107,636","111,748","116,533","122,301","125,661","131,002","138,842","143,917","144,671","151,130",...,"167,712","172,078","177,994","183,581","190,323","195,618","207,999","207,211","217,267","237,720"
Property income received,"116,942","109,346","108,675","113,209","122,970","137,105","153,667","160,013","152,106","152,519",...,"175,342","181,876","198,218","189,502","202,189","202,278","217,587","212,221","215,883","241,202"
Less: property income paid,"41,204","37,300","39,081","40,156","43,309","52,632","61,313","63,921","55,559","54,143",...,"56,232","55,857","56,033","56,405","60,186","70,213","79,808","72,579","66,922","85,866"
Current transfers received,"145,676","147,574","153,189","160,966","165,651","182,779","194,544","204,188","218,275","232,400",...,"258,527","266,153","288,200","307,078","320,918","334,066","346,107","468,640","442,548","423,818"
Less: current transfers paid,"288,042","285,566","296,677","317,236","342,072","361,200","391,983","399,901","385,266","389,755",...,"457,739","478,843","503,246","515,135","530,401","559,134","580,120","583,975","628,799","679,310"
Social transfers in kind (STiK),"160,186","169,696","178,804","186,454","196,284","210,433","221,609","237,315","248,043","257,248",...,"284,952","293,102","302,807","312,884","324,515","336,961","349,855","369,336","396,554","429,133"
Social transfers in kind (STiK): education,"54,355","56,821","59,163","61,929","65,407","70,876","72,755","76,991","80,679","83,671",...,"91,034","93,513","95,214","97,284","101,239","105,131","108,075","112,949","114,611","122,578"
Social transfers in kind (STiK): health,"73,275","77,820","83,061","86,672","90,590","96,801","104,198","111,759","118,734","124,275",...,"139,633","144,998","150,809","155,903","161,159","165,903","172,933","185,450","210,157","227,467"
Social transfers in kind (STiK): other,"32,556","35,055","36,580","37,853","40,287","42,756","44,656","48,565","48,630","49,302",...,"54,285","54,591","56,784","59,697","62,117","65,927","68,847","70,937","71,786","79,088"
Adjusted household disposable income,"775,472","812,280","842,043","881,692","917,794","984,808","1,037,930","1,099,719","1,132,826","1,185,339",...,"1,331,743","1,374,756","1,432,682","1,445,647","1,513,881","1,561,880","1,630,217","1,756,696","1,841,123","1,949,826"
Household final consumption expenditure (HFCE),"615,180","651,605","681,206","712,940","752,414","793,640","842,023","878,505","881,692","926,716",...,"1,038,084","1,086,255","1,122,080","1,153,666","1,209,153","1,260,445","1,300,816","1,227,897","1,327,636","1,469,670"
Food and non-alcoholic beverages,"59,698","62,227","64,646","67,044","69,305","72,227","75,314","79,394","84,166","86,223",...,"94,538","98,670","102,658","105,137","109,628","111,574","115,912","128,000","129,710","138,047"
Alcoholic beverages and tobacco,"27,713","31,002","33,087","34,003","34,130","34,294","34,907","35,605","36,033","37,477",...,"40,679","42,050","43,354","44,523","45,376","48,672","48,571","50,546","51,010","51,749"
Clothing and footwear,"30,229","31,099","31,763","32,559","33,712","35,512","37,171","37,507","36,964","38,677",...,"42,358","44,626","47,299","47,876","49,289","61,997","63,586","50,408","58,853","69,437"
"Housing, water, electricity, gas and other fuels","139,341","145,400","153,520","160,413","168,562","177,060","188,322","200,145","205,828","214,534",...,"244,457","257,191","266,997","275,833","288,655","275,918","290,065","302,490","315,491","341,619"
"Furnishings, household equipment and other goods and services related to the dwelling and property","35,912","38,516","40,551","42,785","44,873","48,180","50,974","52,639","52,060","53,422",...,"55,877","58,285","60,547","62,858","65,200","76,452","79,251","84,579","93,833","97,809"
Health,"21,548","23,418","24,760","26,646","28,720","31,246","33,824","35,944","37,843","39,809",...,"44,037","45,717","47,935","50,188","52,376","51,350","53,421","49,194","53,959","59,541"
Transport,"90,542","97,163","101,244","105,296","113,683","120,288","128,871","134,707","125,375","137,860",...,"163,831","172,794","172,494","176,475","189,321","208,408","209,236","162,733","186,865","221,035"
Communications,"13,672","15,134","15,788","16,811","18,071","19,243","20,175","21,030","22,551","23,423",...,"26,831","28,184","29,495","30,697","33,112","32,218","33,337","33,158","33,534","35,056"
Recreation and culture,"61,600","64,807","67,024","69,501","72,867","76,571","80,747","83,203","83,559","86,079",...,"90,358","92,395","94,536","95,717","97,781","112,177","114,121","108,513","119,676","131,778"
Education,"6,346","6,936","7,873","8,326","8,991","9,562","10,189","10,973","11,838","12,578",...,"15,168","15,012","15,786","16,551","20,681","16,110","16,910","16,390","16,801","18,093"
"Food, beverage and accommodation services","45,449","47,042","48,631","50,961","54,283","57,591","61,374","64,439","64,620","67,606",...,"77,153","80,380","83,572","85,392","86,508","96,227","100,436","68,985","80,968","106,738"
Insurance and financial services,"51,954","55,832","57,839","62,240","66,978","71,411","77,358","78,026","74,669","80,704",...,"88,828","94,556","98,811","101,962","108,202","103,247","106,821","109,557","118,290","121,458"
Miscellaneous goods and services,"31,176","33,029","34,480","36,355","38,239","40,455","42,797","44,893","46,186","48,324",...,"53,969","56,395","58,596","60,457","63,024","66,095","69,149","63,344","68,646","77,310"
Social transfers in kind (STiK),"160,186","169,696","178,804","186,454","196,284","210,433","221,609","237,315","248,043","257,248",...,"284,952","293,102","302,807","312,884","324,515","336,961","349,855","369,336","396,554","429,133"
Social transfers in kind (STiK): education,"54,355","56,821","59,163","61,929","65,407","70,876","72,755","76,991","80,679","83,671",...,"91,034","93,513","95,214","97,284","101,239","105,131","108,075","112,949","114,611","122,578"
Social transfers in kind (STiK): health,"73,275","77,820","83,061","86,672","90,590","96,801","104,198","111,759","118,734","124,275",...,"139,633","144,998","150,809","155,903","161,159","165,903","172,933","185,450","210,157","227,467"
Social transfers in kind (STiK): other,"32,556","35,055","36,580","37,853","40,287","42,756","44,656","48,565","48,630","49,302",...,"54,285","54,591","56,784","59,697","62,117","65,927","68,847","70,937","71,786","79,088"
Household actual final consumption,"775,366","821,301","860,010","899,394","948,698","1,004,073","1,063,632","1,115,820","1,129,735","1,183,964",...,"1,323,036","1,379,357","1,424,887","1,466,550","1,533,668","1,597,406","1,650,671","1,597,233","1,724,190","1,898,803"
Change in pension entitlements,"29,643","29,444","32,376","35,213","41,620","39,979","43,385","45,397","38,057","38,076",...,"44,876","46,439","43,260","43,138","43,728","43,259","47,476","39,000","41,658","41,660"
Household net saving,"29,749","20,423","14,409","17,511","10,716","20,714","17,683","29,296","41,148","39,451",...,"53,583","41,838","51,055","22,235","23,941","7,733","27,022","198,463","158,591","92,683"

In [77]:
df_1 = df.transpose()
df_1

Segment,Household disposable income,Compensation of employees,Net mixed income,Property income received,Less: property income paid,Current transfers received,Less: current transfers paid,Social transfers in kind (STiK),Social transfers in kind (STiK): education,Social transfers in kind (STiK): health,...,"Food, beverage and accommodation services",Insurance and financial services,Miscellaneous goods and services,Social transfers in kind (STiK),Social transfers in kind (STiK): education,Social transfers in kind (STiK): health,Social transfers in kind (STiK): other,Household actual final consumption,Change in pension entitlements,Household net saving
2001,"615,286","574,278","107,636","116,942","41,204","145,676","288,042","160,186","54,355","73,275",...,"45,449","51,954","31,176","160,186","54,355","73,275","32,556","775,366","29,643","29,749"
2002,"642,584","596,782","111,748","109,346","37,300","147,574","285,566","169,696","56,821","77,820",...,"47,042","55,832","33,029","169,696","56,821","77,820","35,055","821,301","29,444","20,423"
2003,"663,239","620,600","116,533","108,675","39,081","153,189","296,677","178,804","59,163","83,061",...,"48,631","57,839","34,480","178,804","59,163","83,061","36,580","860,010","32,376","14,409"
2004,"695,238","656,154","122,301","113,209","40,156","160,966","317,236","186,454","61,929","86,672",...,"50,961","62,240","36,355","186,454","61,929","86,672","37,853","899,394","35,213","17,511"
2005,"721,510","692,609","125,661","122,970","43,309","165,651","342,072","196,284","65,407","90,590",...,"54,283","66,978","38,239","196,284","65,407","90,590","40,287","948,698","41,620","10,716"
2006,"774,375","737,321","131,002","137,105","52,632","182,779","361,200","210,433","70,876","96,801",...,"57,591","71,411","40,455","210,433","70,876","96,801","42,756","1,004,073","39,979","20,714"
2007,"816,321","782,564","138,842","153,667","61,313","194,544","391,983","221,609","72,755","104,198",...,"61,374","77,358","42,797","221,609","72,755","104,198","44,656","1,063,632","43,385","17,683"
2008,"862,404","818,108","143,917","160,013","63,921","204,188","399,901","237,315","76,991","111,759",...,"64,439","78,026","44,893","237,315","76,991","111,759","48,565","1,115,820","45,397","29,296"
2009,"884,783","810,556","144,671","152,106","55,559","218,275","385,266","248,043","80,679","118,734",...,"64,620","74,669","46,186","248,043","80,679","118,734","48,630","1,129,735","38,057","41,148"
2010,"928,091","835,940","151,130","152,519","54,143","232,400","389,755","257,248","83,671","124,275",...,"67,606","80,704","48,324","257,248","83,671","124,275","49,302","1,183,964","38,076","39,451"
2011,"962,102","881,146","157,679","162,165","54,580","236,877","421,185","270,314","87,614","130,683",...,"70,736","84,381","50,429","270,314","87,614","130,683","52,017","1,237,392","46,937","41,961"
2012,"1,001,254","921,492","162,931","170,336","55,598","246,062","443,969","276,781","88,828","134,448",...,"74,115","84,478","52,411","276,781","88,828","134,448","53,505","1,274,836","47,452","50,651"
2013,"1,046,791","959,181","167,712","175,342","56,232","258,527","457,739","284,952","91,034","139,633",...,"77,153","88,828","53,969","284,952","91,034","139,633","54,285","1,323,036","44,876","53,583"
2014,"1,081,654","996,247","172,078","181,876","55,857","266,153","478,843","293,102","93,513","144,998",...,"80,380","94,556","56,395","293,102","93,513","144,998","54,591","1,379,357","46,439","41,838"
2015,"1,129,875","1,024,742","177,994","198,218","56,033","288,200","503,246","302,807","95,214","150,809",...,"83,572","98,811","58,596","302,807","95,214","150,809","56,784","1,424,887","43,260","51,055"
2016,"1,132,763","1,024,142","183,581","189,502","56,405","307,078","515,135","312,884","97,284","155,903",...,"85,392","101,962","60,457","312,884","97,284","155,903","59,697","1,466,550","43,138","22,235"
2017,"1,189,366","1,066,523","190,323","202,189","60,186","320,918","530,401","324,515","101,239","161,159",...,"86,508","108,202","63,024","324,515","101,239","161,159","62,117","1,533,668","43,728","23,941"
2018,"1,224,919","1,122,304","195,618","202,278","70,213","334,066","559,134","336,961","105,131","165,903",...,"96,227","103,247","66,095","336,961","105,131","165,903","65,927","1,597,406","43,259","7,733"
2019,"1,280,362","1,168,597","207,999","217,587","79,808","346,107","580,120","349,855","108,075","172,933",...,"100,436","106,821","69,149","349,855","108,075","172,933","68,847","1,650,671","47,476","27,022"
2020,"1,387,360","1,155,842","207,211","212,221","72,579","468,640","583,975","369,336","112,949","185,450",...,"68,985","109,557","63,344","369,336","112,949","185,450","70,937","1,597,233","39,000","198,463"
2021,"1,444,569","1,264,592","217,267","215,883","66,922","442,548","628,799","396,554","114,611","210,157",...,"80,968","118,290","68,646","396,554","114,611","210,157","71,786","1,724,190","41,658","158,591"
2022,"1,520,693","1,383,129","237,720","241,202","85,866","423,818","679,310","429,133","122,578","227,467",...,"106,738","121,458","77,310","429,133","122,578","227,467","79,088","1,898,803","41,660","92,683"

In [14]:
cpi_df = pd.read_csv('./Resources/canada_CPI.csv')
cpi_df.head()

,OBSERVATIONS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,date,INDINF_CPI_Q,INDINF_CPI_TRIM_Q,INDINF_CPI_MEDIAN_Q,INDINF_CPI_COMMON_Q
1,1993Q1,2.2,2,2,1.8
2,1993Q2,1.8,1.9,1.9,1.7
3,1993Q3,1.8,1.8,1.7,1.4
4,1993Q4,1.8,1.8,1.7,1.5

In [15]:
cpi_df.columns = cpi_df.iloc[0]

In [16]:
cpi_df.head()

,date,INDINF_CPI_Q,INDINF_CPI_TRIM_Q,INDINF_CPI_MEDIAN_Q,INDINF_CPI_COMMON_Q
0,date,INDINF_CPI_Q,INDINF_CPI_TRIM_Q,INDINF_CPI_MEDIAN_Q,INDINF_CPI_COMMON_Q
1,1993Q1,2.2,2,2,1.8
2,1993Q2,1.8,1.9,1.9,1.7
3,1993Q3,1.8,1.8,1.7,1.4
4,1993Q4,1.8,1.8,1.7,1.5

In [17]:
cpi_df = cpi_df.iloc[1:]
cpi_df.head()

,date,INDINF_CPI_Q,INDINF_CPI_TRIM_Q,INDINF_CPI_MEDIAN_Q,INDINF_CPI_COMMON_Q
1,1993Q1,2.2,2,2,1.8
2,1993Q2,1.8,1.9,1.9,1.7
3,1993Q3,1.8,1.8,1.7,1.4
4,1993Q4,1.8,1.8,1.7,1.5
5,1994Q1,0.5,1.5,1.6,1.3

In [43]:
import requests
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol=CGR.TRT&outputsize=full&apikey=QNUCGT4HIOG7WH50&datatype=csv'
r = requests.get(url)
data = pd.read_csv(url)
data

      timestamp   open   high    low  close  volume
0    2024-01-16  28.26  28.51  27.82  28.13   19901
1    2023-12-29  26.78  28.80  26.78  28.24   73100
2    2023-11-30  24.63  26.88  24.54  26.86   65800
3    2023-10-31  24.87  25.30  23.95  24.60   57400
4    2023-09-29  26.66  26.76  24.46  24.85   71100
..          ...    ...    ...    ...    ...     ...
180  2009-01-30  14.17  14.23  12.20  12.50   14438
181  2008-12-31  12.95  14.71  12.50  14.38   44873
182  2008-11-28  15.24  15.41  11.68  13.73  196516
183  2008-10-28  18.75  19.03  14.34  14.43  156889
184  2008-09-30  20.88  20.88  18.01  18.87   14158

[185 rows x 6 columns]